from slide_analysis_service.utils.functions import compose
from slide_analysis_service.utils.functions import get_descriptor_class_by_name
from slide_analysis_service.utils.functions import get_tiles_coords_from_indexes
from slide_analysis_service.utils.functions import get_similarity_map_shape
from slide_analysis_service.utils.tile_class import Tile
